### ISSUE TITLE
is it possible to install on macOs?

### ISSUE THREAD

**Issue by guiaramos** [mohitsinghs/dotfiles#3]
I am getting this error:
```bash
curl -fsSL sh.mohitsingh.in | bash         

Password:
Asia/Kolkata
find: /etc/apt/: No such file or directory
sudo: apt-add-repository: command not found
```

**Comment by mohitsinghs** [comment]
Unfortunately No. I no longer use macOS and switched to Linux a while back.
[This commit](https://github.com/mohitsinghs/dotfiles/tree/d9a2c440e4f13fda8bb0f7e3dbd08218e4bc9283) contains macOS setup if that helps.
